In [2]:
import torch
from torch.nn import Linear
import torch.nn as nn

In [4]:
# Cuando usamos requires grad, esto lo que busca es que el tensor guarde todas las operaciones
# Que se realizarán en el, muy util por si hacemos un proceso tipo backward y necesitamos conocer
# SU historia

# Estamos viendo un modelo de regresión lineal simple
# yhat = bias + weight * x
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(-2.5, requires_grad=True)

In [5]:
def forward(x):
    out = b + w*x
    return out


In [6]:
x = torch.tensor([[1.0],[2.5]])

In [7]:
forward(x)

tensor([[-1.5000],
        [ 0.0000]], grad_fn=<AddBackward0>)

In [8]:
# También podemos realizarlo a través de los métodos de Pytorch,
# En este caso tenemos especificamente a la función Linear
# In features se refiere a la cantidad de elementos que ingresan columnas
# Out Features, se refiere a la cantidad que sale

# Aquí ya está definido el forward, que es el predict de torch no debemos llamarlo
torch.manual_seed(1)

model = Linear(in_features=1, out_features=1)

model(x)

tensor([[0.0739],
        [0.8468]], grad_fn=<AddmmBackward0>)

In [32]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5300]], requires_grad=True), Parameter containing:
tensor([-0.4400], requires_grad=True)]


In [ ]:
# Finalmente tenemos los objetos para crear clases más profuncas de Torch
# Es una herramienta donde básicamente podemos crear modelos más complejos 
# Utilizando todas las funcionalidades de Torch
# El punto clave es que debemos definir el forward

class LR(nn.Module):
    def __init__(self, in_size, out_size):
        super(LR, self).__init__() # Comando ultra importante, básicamente activa las funcionalidades de torch en mi clase
        self.model = nn.Linear(in_size, out_size)
        
    def forward(self, x):
        out = self.model(x)
        return out

In [28]:
model = LR(1,1)
model(x)

tensor([[0.0166],
        [0.2251]], grad_fn=<AddmmBackward0>)

In [29]:
# Para ver los parámetros usamos state_dict
# Este diccionario nos permite también cambiar el estado
print(model.state_dict())

model.state_dict()['model.weight'].data[0] = torch.tensor([.53])
model.state_dict()['model.bias'].data[0] = torch.tensor([-.44])

print(model.state_dict())

OrderedDict({'model.weight': tensor([[0.1390]]), 'model.bias': tensor([-0.1224])})
OrderedDict({'model.weight': tensor([[0.5300]]), 'model.bias': tensor([-0.4400])})
