In [1]:
import torch

# Regresion Lineal
Ya la conocemos, se define como $$\hat{y} = b + w \times x$$

Donde tenemos el error o bias $b$ y el peso $w$

In [2]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [3]:
def forward(x):
    y = b + w*x
    return y

In [4]:
x = torch.tensor(1.0)

In [6]:
yhat = forward(x)
print(yhat)

tensor(1., grad_fn=<AddBackward0>)


In [13]:
x = torch.tensor([[1.0],[2.0]])
yhat = forward(x)
print(yhat)

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [8]:
from torch.nn import Linear

In [9]:
torch.manual_seed(1)

model = Linear(in_features = 1, out_features = 1)


In [11]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [15]:
yhat = model(x)
yhat

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)

## Custom Modules
Básicamente es un objeto que nos permite crear modelos más complejos desde objetos ya de torch

In [16]:
import torch.nn as nn

In [21]:
class LR(nn.Module):
    def __init__(self, in_features, out_features):
        super(LR,self).__init__()
        self.linear = nn.Linear(in_features = in_features, out_features = out_features)

    def forward(self, x):
        out = self.linear(x)
        return out

In [22]:
model = LR(1,1) 

In [24]:
model(x)

tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward0>)

In [33]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[0.5153]])),
             ('linear.bias', tensor([-0.4400]))])

In [29]:
model.state_dict()['linear.weight'].data[0] = torch.tensor([0.5153])
model.state_dict()['linear.bias'].data[0] = torch.tensor([-0.44])

In [30]:
model(x)

tensor([[0.0753],
        [0.5906]], grad_fn=<AddmmBackward0>)